Feature/reservation
Soongsil-Developers/22sdc-terrace-server pull request #3
Opened 2022-09-14 11:25 UTC by seoseoseodabin

## 개요
- 테라스 예약 생성
- 테라스 정보 가져오기

## 작업 사항
- 예약이 들어오면 user_id랑 terrace_id를 받아서 db reservation 테이블에 예약 정보가 생성되도록 했습니다. talend api로 테스트 해보려고 했는데 아직 로그인이 안 돼서 401 에러가 뜨는데, 나중에 테스트 해보고 수정하도록 하겠습니다.
- 사용 가능한 테라스를 화면에 표시하려면 테라스 정보가 필요할 것 같아서 모든 테라스 정보를 List로 한꺼번에 반환해주는 메소드를 만들었습니다.

제가 브랜치 분리하는 걸 깜빡해서 기능이 분리가 안 됐어요.. 죄송합니다. 다음부터는 주의할게요!!

2022-09-15 04:27 UTC, sang-w0o requested changes

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/controller/ReservationApiController.kt
> +    }
`@RestController`가 적용되어 있으면 `ReservationDto`를 `ResponseEntity<T>`로 묶어서 반환해줄 필요가 없어요!

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/controller/ReservationApiController.kt
> +    }
HTTP status는 아래처럼 지정하면 돼요!

```kt
@PostMapping
@ResponseStatus(HttpStatus.CREATED)
fun create(@RequestBody requestDto: ReservationDto): ReservationDto {
    return reservationService.createReservation(requestDto)
}

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/domain/ReservationRepository.kt
> +import java.time.LocalDateTime
불필요한 import가 많이 추가되었는데, 모두 제거해주세요!

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/dto/ReservationDto.kt
> +    val userId: String
이 클래스가 request body를 담는 클래스로 동작하기 때문에, id는 항상 null일 것 같아요!
따라서 이런 경우, id 필드를 아예 제거하는게 좋을 것 같아요!

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/controller/ReservationApiController.kt
> +    }
지금은 `reservationService.createReservation()`이 `Reservation`을 반환하지만 쓰이고 있지는 않네요!
더 나은 방법으로 무엇이 있을까요~?

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/service/ReservationServiceImpl.kt
> +) : ReservationService{
```suggestion
) : ReservationService {
```

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/service/ReservationServiceImpl.kt
> +    }
`GlobalExceptionHandler`가 있음에도 이렇게 비즈니스 로직이 try-catch로 감싸여져 있는 코드는 악취가 나네요 ㅎㅎ
그리구 `InvalidAccessException`은 auth 관련된 예외이기에, terrace 하위에 exception이라는 패키지를 만들고, `InvalidAccessException`을 대체할 수 있는 예외 클래스를 정의해 사용하는게 좋아보여요!

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/service/ReservationServiceImpl.kt
> +            val user: User = userRepository.getById(reservationDto.userId)
try-catch를 아래처럼 없앨 수 있어요.

```suggestion
            val terrace: Terrace = terraceRepository.findById(reservationDto.terraceId).orElseThrow { TerraceIdNotFoundException() }
            val user: User = userRepository.findById(reservationDto.userId).orElseThrow { UserIdNotFoundException() }
```

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/dto/ReservationDto.kt
> +    val userId: String
추가적으로 JWT에 이미 user id가 claim으로 들어있기 때문에, request body로 받지 않아도 활용할 수 있어요!

2022-09-15 04:27 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/terrace/dto/TerraceDto.kt
> +}
```suggestion
data class TerraceDto (
    val terrace_id: Int,
    val floor: Int,
    val status: TerraceStatus
)
```

2022-09-15 15:09 UTC, seoseoseodabin commented on src/main/kotlin/com/dev_camp/reservation/dto/ReservationDto.kt
> +    val userId: String
상우님 코드 읽어보고 서치 해보니까 요청을 처리할 때 UserInfoArgumentResolver가 메소드 파라미터에 값을 주입해준다는데, 그냥 UserDto 파라미터만 추가하면 되는 건가요? 아니면 @RequestHeader로 헤더를 받아와서 직접 처리해야 하는 건가요?

2022-09-16 03:15 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/dto/ReservationDto.kt
> +    val userId: String
아니요! 
controller 부분에서

```kt
@PostMapping
fun foo(@LoggedInUser user: User): Unit {
    // TODO
}
```

이런 식으로 받아올 수 있어요! 구현 방법은 코드 뜯어보시면 알 수 있을거에요!

2022-09-16 03:18 UTC, sang-w0o requested changes

2022-09-16 03:18 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/controller/ReservationApiController.kt
> +    fun create(@PathVariable("terrceId") terraceId: Int, userId: String) : Reservation {
여기 오타가 있는 것 같네요! (terrceId)

그리고 변수명이 pathVariable (`{terraceId}`)와 일치하면 `@PathVariable`에 값을 지정해줄 필요가 없어요!

```kt
@PostMapping("/{something}")
fun foo(@PathVariable something: String) { 
    //..
}
```

위 예시 코드에서는 something이 들어갈 변수명과 path variable에 있는 이름이 동일해서 생략 가능한거에요!

2022-09-16 03:18 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/terrace/controller/TerraceApiController.kt
> +    }
여기도 마찬가지로 `ResponseEntity<T>`로 묶어줄 필요가 없겠네요

2022-09-16 03:18 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/terrace/dto/TerraceDto.kt
> +    val terrace_id: Int,
이 변수는 왜 snake case로 명명되어 있나요?

2022-09-17 12:23 UTC, seoseoseodabin commented
@sang-w0o 저 이거 머지해도 될까요?

2022-09-17 13:21 UTC, sang-w0o requested changes
마지막 하나만 확인하시고, 반영하신 후 머지해주세요!

2022-09-17 13:21 UTC, sang-w0o commented on src/main/kotlin/com/dev_camp/reservation/dto/ReservationDto.kt
> +data class ReservationDto(
이 클래스 사용되나요? userId가 필요 없는 거 아니에요?

2022-09-17 13:27 UTC, seoseoseodabin commented on src/main/kotlin/com/dev_camp/reservation/dto/ReservationDto.kt
> +data class ReservationDto(
아 사용이 안되네요 지울게요!

2022-09-17 13:30 UTC, merged